# Nome da Aplicação
spring.application.name=api-raizes-do-nordeste

# Configurações do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:raizesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o Console do H2 (Para visualizar o banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa a sessão aberta na View (Evita warning de OSIV e melhora performance)
spring.jpa.open-in-view=false

# Springdoc / Swagger UI Configurações
springdoc.swagger-ui.path=/swagger-ui.html